server:
  port: 8080

spring:
  application:
    name: file
  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  grpc:
    server:
      enabled: on
      port: 9090

logging:
  level:
    org.hibernate: debug
    org.liquibase: debug
  file:
    path: ./logs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost}:${EUREKA_PORT:8080}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      grpc.port: ${grpc.server.port:9090}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: "habilisadi_file"
